### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by thereallacas** [thereallacas/commons-rdf#1]
CI beüzemelése
Első lépésként aktiváltam a travist. Egy revert commit történt közben, ezért a master ág tesztelése meg is történt, hibátlan eredménnyel

**Comment by thereallacas** [comment]
Miután [https://github.com/Norberts11](url) kijavított pár Sonarqube által jelzett hibát, pushol a repoba egy külön branchen és a Travis tudja teszteli az ágat
A többiről a Sonarqube issue ban.

**Comment by thereallacas** [comment]
A konkrét commit az új, sonarfix nevű branchen:
[https://github.com/thereallacas/commons-rdf/commit/ec01f0a93a490dd152ffe62d1908d28024f7b811](url)

[https://github.com/Norberts11](url) ezután végrehajt egy pull requestet a főágra, amit személyesen fogok ellenőrizni.

**Comment by thereallacas** [comment]
A travis ci ellenőrizte a pull requestet, és nem talált hibát

**Comment by thereallacas** [comment]
Egy újabb hiba javítása, ezúttal reviewt is kérnek tőlem. Ugyanaz a folyamat fog lezajlani, a Travis ellenőrzi az új ágat, majd a pull requestet is.

**Comment by thereallacas** [comment]
Megtörtént a review és az ellenőrzés. A kód elentős változtatásokon ment keresztül, melynek következtében gyorsabb és hatékonyabb lett.

**Comment by NorbertSomogyi** [comment]
A Travis CI beüzemelése sikeres volt, a projektet minden változás után ellenőrzi, hogy sikeresen lefutnak-e a tesztek, és megy-e a fordítás. A feladatot elvégzettnek tekintem.

**Comment by thereallacas** [comment]
A pull request merging megtörtént, minden rendben

**Comment by thereallacas** [comment]
jó minden
jók a programok

**Comment by micskeiz** [comment]
A "CI beüzemelése, ha még nincs (Travis, AppVeyor...)" feladat arra vonatkozik, ha még nincs meg a .travis.yml, és azt nektek kell összerakni. Ez ennél a projektnél adott volt, tehát kérlek válasszatok másik feladatot. Azért van 5 megadva, hogy minden projektnél lehessen olyat találni, ami még igényel lényegi munkát.
