### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by ietbbgy** [thereallacas/commons-rdf#11]
Add some unit tests to improve test coverage reported by Sonarqube.

**Comment by ietbbgy** [comment]
Unit tests for the api module have been added and merged into the master branch.

**Comment by ietbbgy** [comment]
Unit tests for the jena module have been added, can be reviewed on the jenaunittest branch.

**Comment by NorbertSomogyi** [comment]
Hozzáadtam néhány tesztet, egy komplex teszten jelenleg dolgozok, egyelőre még nincs publikálható állapotban.
A tesztek commitjai: 09a95ba4c8b207654343e549f7e32fa9614d5836, 8bb0aac6717ecd85b7a147d4bb54ae0450d9a4fe

**Comment by thereallacas** [comment]
A tesztlefedettségek 65 ről 72 százalékosra mentek fel. Lehet vajon még ezen javítani?

**Comment by NorbertSomogyi** [comment]
Nyilván lehet, vannak azonban kézzel nagyon nehezen tesztelhető részei a projektnek, ilyenek tipikusan a parserek.
