### ISSUE TITLE
Az AbstractRDFParserTest osztály két tesztje failel

### ISSUE THREAD

**Issue by egunsoma** [thereallacas/commons-rdf#14]
Az alábbi tesztek failelnek az én gépemen:
```
Failed tests: 
  AbstractRDFParserTest.parseFile:121 expected:<<file:///[]var/folders/gx/qs51h...> but was:<<file:///[private/]var/folders/gx/qs51h...>
  AbstractRDFParserTest.parseFileContentType:165 expected:<<file:///[]var/folders/gx/qs51h...> but was:<<file:///[private/]var/folders/gx/qs51h...>
```
Környezet: Mac OSX
Reprodukálás: `mvn clean install`

**Comment by egunsoma** [comment]
Eddig úgy néz ki Mac specifikus a hiba, a mindkét assert a file pathok összehasonlításával száll el, az elvárt viselkedés szerint a **var** folderbe kell kerülnie a temp fileoknak, Mac-en viszont a **private/var** folderbe kerül.

Hogy mi ez a private folder, arról [itt](https://discussions.apple.com/thread/3757828?tstart=0) találtam leírást.

**Comment by egunsoma** [comment]
Lehet ennek köze ahhoz, hogy _base_ predicate optional? Az AbstractRDFParserTest.checkGraph() is [máshogy assertel](https://github.com/thereallacas/commons-rdf/blob/master/simple/src/test/java/org/apache/commons/rdf/simple/experimental/AbstractRDFParserTest.java#L105) _base_ esetében. 

**Egyáltalán szükség van erre az assertre van ennél a két tesztnél?**

Source 
`<file:///var/folders/gx/qs51hf715jl_bljk88cc1hdc0000gn/T/test8421380003520334321.nt>`
  
Base `<file:///private/var/folders/gx/qs51hf715jl_bljk88cc1hdc0000gn/T/test8421380003520334321.nt>`

**Comment by egunsoma** [comment]
@thereallacas légyszíves reviewzd a #17-t

**Comment by thereallacas** [comment]
Megnéztem, szerintem ez megoldja a problémát, ha egyszerűen átugorjuk ezeket a teszteket mac rendszerű gépek esetén. Egyátalán az ötlet hogy OS specifikus path okat vizsgálunk a tesztekben már fishy számomra
