### ISSUE TITLE
Kódanalízis Codescene-nel

### ISSUE THREAD

**Issue by egunsoma** [thereallacas/commons-rdf#15]
A Craft konferencián hallgattam meg egy előadást erről a [tool](https://codescene.io/)-ról, ha a kötelező dolgokkal már megvagyuk kipróbálhatnánk hogy számunkra használható-e.

Az előbb @thereallacas segített kipróbálni, public projectekre ingyenes Githubon.

**Comment by thereallacas** [comment]
Kipróbáltam, beizzítottam a codescenet a projektre

**Comment by thereallacas** [comment]
https://codescene.io/projects/1172/jobs/2423/results
Itt vannak az eredmények. Mindjárt elemzem őket

**Comment by egunsoma** [comment]
Elkezdtem ledokumentálni a kapott eredményeket.
https://github.com/thereallacas/commons-rdf/wiki/CODESCENE.IO

**Comment by egunsoma** [comment]
Végeztem a dokumentálással, @thereallacas kérlek nézd át, egyetértesz-e, találsz benne javítani valót?

**Comment by thereallacas** [comment]
Jónak látom azokat a dolgokat amiket leírtál. Ennek alapján ránézek a sárgával jelölt hotspotokra, és átnézem őket manuálisan. A piros hotspotot látom elkezdted javítani
