### ISSUE TITLE
Graph remove test refaktorálása

### ISSUE THREAD

**Issue by egunsoma** [thereallacas/commons-rdf#16]
Az alábbi [tesztet](https://github.com/thereallacas/commons-rdf/blob/master/api/src/test/java/org/apache/commons/rdf/api/AbstractGraphTest.java#L233) a codescene.io hotspotnak jelezte, ami azt jelenti, hogy a kód viszonylag nagy komplexitású, és gyakran van rajta fejlesztői munka.

Ezt fogom refaktorálni a mindenki által ismert Arrange-Act-Assert mintára, hogy karbantarthatóbb legyen a kód.

**Comment by thereallacas** [comment]
egyetértek, valóban átláthatóbb lenne így
