### ISSUE TITLE
SonarQube kódanalizátor futtatása, a futás eredményének átvizsgálása, hibák javítása

### ISSUE THREAD

**Issue by NorbertSomogyi** [thereallacas/commons-rdf#2]
A SonarQube statikus kódanalizátor mavennel való integrálása után az analizátort lefuttattam, mely felfedett 44 hibát a kódban.
A feladat ezen hibák közül néhánynak a javítása.

**Comment by NorbertSomogyi** [comment]
Az AbstractRDFParser.java fileban az 510. sorban nem optimális lastIndexOf(String) hívás található, le kell cserélni lastIndexOf(char)-ra, mert az gyorsabb.

**Comment by thereallacas** [comment]
Itt a file
[https://github.com/thereallacas/commons-rdf/blob/master/simple/src/main/java/org/apache/commons/rdf/simple/experimental/AbstractRDFParser.java](url)
Itt a kérdéses kód:
` final String filenameStr = fileName.toString();
final int last = filenameStr.lastIndexOf(".");
if (last > -1) {
return Optional.of(filenameStr.substring(last));
}`

**Comment by NorbertSomogyi** [comment]
Javítottam, ec01f0a93a490dd152ffe62d1908d28024f7b811

**Comment by NorbertSomogyi** [comment]
A W3CRDFSyntax.java-ban a 193. sorban egyszerűsíthető string equality check van, lecseréltem egyszerűbb változatra 5e2f0317b0aa22597830daf554c039e1c5dfd1c4

**Comment by thereallacas** [comment]
Összegző értékelés [https://github.com/Norberts11](url) munkájáról:
Úgy érzem a Sonarqube használatával számos, a program futását egyértelműen lassító kódrészletet fedett fel és javított ki, így összességében azt kell mondjam , a feladat végrehajtása sikeres volt.

**Comment by micskeiz** [comment]
"Úgy érzem a Sonarqube használatával számos, a program futását egyértelműen lassító kódrészletet fedett fel és javított ki, így összességében azt kell mondjam , a feladat végrehajtása sikeres volt."

Két triviális hibát javítottatok. Ez a Sonar futtatásával együtt mennyi időt igényelt? Maximum fél óra? Nem kell mind a 40 hibát javítani, de kérlek nézzétek meg alaposabban.

**Comment by NorbertSomogyi** [comment]
Az apache/commons/rdf/jena/impl/JenaGraphImpl.java fileban double-checked locking található. Ez veszélyes és kerülendő, mert bizonyos esetekben előfordulhat, hogy részlegesen inicializált objektumra adunk vissza referenciát (részletekért http://www.javaworld.com/article/2074979/java-concurrency/double-checked-locking--clever--but-broken.html?page=2).
Két megoldás kínálkozik: elhagyni a lazy loadingot, vagy szinkronizálni a kérdéses metódust. Mindkét opció lassítja a kódot, de biztonságossá teszi. Talán a szinkronizálás tűnik jobb kompromisszumnak, így ezt fogom implementálni.

**Comment by NorbertSomogyi** [comment]
Néhány javításhoz tartozó commitok:
Double-checked locking: 18ef61df71a908970e208679116009c0f9e219e7
Néhány triviális code smell: a07fb9a3d15870c5c7a484568ff7e01f76308b74, b783bf4c08ca0e1674204ac484990f0c4cb7c55b

**Comment by NorbertSomogyi** [comment]
Néhány hamis jelzést is adott a sonar, melyek "javítása" után a megfelelő tesztek sikertelenül futottak le. Ezek tipikusan az instanceof operator logikai kifejezésekben való eltávolítását szorgalmazták, jelezvén, hogy mindig igazat adnak vissza, de ez nem így van.
A commit, mely néhány instanceofot kiszedett: 8db90928b013aaf822e5b8ddba7d624f06ba0084
A commit, mely revertálta az előbbit: a59273a26c12274ee5ccbd8b91f5da4b9f8d06f8
Megjegyzendő, hogy itt tévedésből a master ágon dolgoztam, ezért volt szükség revertálásra.

**Comment by NorbertSomogyi** [comment]
További hamis jelzést találtam. A projekt gyakran használja a java Optional osztályát (https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html), mely értékeket vagy tartalmaz, vagy nem. Ha tartalmaz, akkor a get() metódusa visszaadja, ha nem, akkor kivételt dob. Ezért minden hívás előtt hívni kell az isPresent() metódusát. Erre példát többek között a következő fileban találhatunk:https://github.com/thereallacas/commons-rdf/blob/master/jena/src/main/java/org/apache/commons/rdf/jena/experimental/JenaRDFParser.java
if (getSourceIri().isPresent()) {
            RDFDataMgr.parse(dest, getSourceIri().get().toString(), baseStr, lang, null);
        }
Ehhez hasonlóan az összes többi jelzett helyen helyesen van használva ez az osztály. Ez összesen 22 hamis hibát eredményezett.
