### ISSUE TITLE
javadoc hibak

### ISSUE THREAD

**Issue by ietbbgy** [thereallacas/commons-rdf#9]
Jelenleg nem buildel a projekt javadoc hibak miatt. Ezt valoszinuleg a javadoc mvn plugin okozza java 8-as kornyezetben. A hibak az api/RDFSyntax.java fajlban vannak.

**Comment by ietbbgy** [comment]
az api projektben a javadoc errorokat kijavitottam, a warningok meg megvannak. kuldok pull requestet

**Comment by thereallacas** [comment]
mergeltem

**Comment by ietbbgy** [comment]
fordul a projekt, legeneralodik a javadoc. bezarom
